// Class NoisePlugin.NoiseBlueprintFunctionLibrary
// Size: 0x28 (Inherited: 0x28)
struct UNoiseBlueprintFunctionLibrary : UBlueprintFunctionLibrary {

	float SelectNoise(float NoiseValue1, float NoiseValue2, float ControlNoise, enum class ESelectInterpType Interpolation, float Falloff, float Threshold, int32_t Steps); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.SelectNoise // (Final|Native|Static|Public|BlueprintCallable|BlueprintPure) // @ game+0x867350
	float Select3Noise(float NoiseValue1, float NoiseValue2, float NoiseValue3, float ControlNoise, enum class ESelectInterpType Interpolation, float Falloff, float LowerThreshold, float UpperThreshold, int32_t Steps); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.Select3Noise // (Final|Native|Static|Public|BlueprintCallable|BlueprintPure) // @ game+0x867090
	float ScaleBiasNoise(float NoiseValue, float Scale, float Bias); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.ScaleBiasNoise // (Final|Native|Static|Public|BlueprintCallable|BlueprintPure) // @ game+0x866f70
	float RadialNoise(float NoiseValue1, float NoiseValue2, enum class ESelectInterpType Interpolation, struct FVector Origin, float Radius, float Falloff, int32_t Steps, struct FVector Coordinates); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.RadialNoise // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintPure) // @ game+0x866ce0
	void GradientPerturbFractal3D(int32_t Seed, float Perturb, float Frequency, float Lacunarity, float Gain, int32_t Octaves, enum class EInterp Interpolation, struct FVector Coordinates, struct FVector OutCoordinates); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.GradientPerturbFractal3D // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintPure) // @ game+0x866a30
	void GradientPerturbFractal2D(int32_t Seed, float Perturb, float Frequency, float Lacunarity, float Gain, int32_t Octaves, enum class EInterp Interpolation, struct FVector2D Coordinates, struct FVector2D OutCoordinates); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.GradientPerturbFractal2D // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintPure) // @ game+0x866780
	void GradientPerturb3D(int32_t Seed, float Perturb, float Frequency, enum class EInterp Interpolation, struct FVector Coordinates, struct FVector OutCoordinates); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.GradientPerturb3D // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintPure) // @ game+0x866580
	void GradientPerturb2D(int32_t Seed, float Perturb, float Frequency, enum class EInterp Interpolation, struct FVector2D Coordinates, struct FVector2D OutCoordinates); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.GradientPerturb2D // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintPure) // @ game+0x866390
	float GetWhiteNoise4D(int32_t Seed, struct FVector4 Cooordinates); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.GetWhiteNoise4D // (Final|Native|Static|Public|HasDefaults|BlueprintCallable|BlueprintPure) // @ game+0x8662b0
	float GetWhiteNoise3D(int32_t Seed, struct FVector Coordinates); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.GetWhiteNoise3D // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintPure) // @ game+0x8661e0
	float GetWhiteNoise2D(int32_t Seed, struct FVector2D Coordinates); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.GetWhiteNoise2D // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintPure) // @ game+0x866110
	float GetValueFractal3D(int32_t Seed, float Frequency, float Lacunarity, float Gain, int32_t Octaves, enum class EInterp Interpolation, enum class EFractalType FractalType, struct FVector Coordinates); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.GetValueFractal3D // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintPure) // @ game+0x865eb0
	float GetValueFractal2D(int32_t Seed, float Frequency, float Lacunarity, float Gain, int32_t Octaves, enum class EInterp Interpolation, enum class EFractalType FractalType, struct FVector2D Coordinates); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.GetValueFractal2D // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintPure) // @ game+0x865c50
	float GetValue3D(int32_t Seed, float Frequency, enum class EInterp Interpolation, struct FVector Coordinates); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.GetValue3D // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintPure) // @ game+0x865b00
	float GetValue2D(int32_t Seed, float Frequency, enum class EInterp Interpolation, struct FVector2D Coordinates); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.GetValue2D // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintPure) // @ game+0x8659b0
	float GetSimplexFractalBlend(int32_t Seed, float Lacunarity, float Gain, int32_t Octaves, struct FVector2D Coordinates); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.GetSimplexFractalBlend // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintPure) // @ game+0x865820
	float GetSimplexFractal3D(int32_t Seed, float Frequency, float Lacunarity, float Gain, int32_t Octaves, enum class EFractalType FractalType, struct FVector Coordinates); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.GetSimplexFractal3D // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintPure) // @ game+0x865600
	float GetSimplexFractal2D(int32_t Seed, float Frequency, float Lacunarity, float Gain, int32_t Octaves, enum class EFractalType FractalType, struct FVector2D Coordinates); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.GetSimplexFractal2D // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintPure) // @ game+0x8653e0
	float GetSimplex4D(int32_t Seed, float Frequency, struct FVector4 Coordinates); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.GetSimplex4D // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintPure) // @ game+0x8652b0
	float GetSimplex3D(int32_t Seed, float Frequency, struct FVector Coordinates); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.GetSimplex3D // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintPure) // @ game+0x865190
	float GetSimplex2D(int32_t Seed, float Frequency, struct FVector2D Coordinates); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.GetSimplex2D // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintPure) // @ game+0x865080
	float GetPerlinFractal3D(int32_t Seed, float Frequency, float Lacunarity, float Gain, int32_t Octaves, enum class EInterp Interpolation, enum class EFractalType FractalType, struct FVector Coordinates); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.GetPerlinFractal3D // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintPure) // @ game+0x864e20
	float GetPerlinFractal2D(int32_t Seed, float Frequency, float Lacunarity, float Gain, int32_t Octaves, enum class EInterp Interpolation, enum class EFractalType FractalType, struct FVector2D Coordinates); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.GetPerlinFractal2D // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintPure) // @ game+0x864bc0
	float GetPerlin3D(int32_t Seed, float Frequency, enum class EInterp Interpolation, struct FVector Coordinates); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.GetPerlin3D // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintPure) // @ game+0x864a70
	float GetPerlin2D(int32_t Seed, float Frequency, enum class EInterp Interpolation, struct FVector2D Coordinates); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.GetPerlin2D // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintPure) // @ game+0x864920
	float GetCubicFractal3D(int32_t Seed, float Frequency, float Lacunarity, float Gain, int32_t Octaves, enum class EFractalType FractalType, struct FVector Coordinates); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.GetCubicFractal3D // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintPure) // @ game+0x864700
	float GetCubicFractal2D(int32_t Seed, float Frequency, float Lacunarity, float Gain, int32_t Octaves, enum class EFractalType FractalType, struct FVector2D Coordinates); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.GetCubicFractal2D // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintPure) // @ game+0x8644e0
	float GetCubic3D(int32_t Seed, float Frequency, struct FVector Coordinates); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.GetCubic3D // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintPure) // @ game+0x8643c0
	float GetCubic2D(int32_t Seed, float Frequency, struct FVector2D Coordinates); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.GetCubic2D // (Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintPure) // @ game+0x8642b0
	float BlendNoise(float NoiseValue1, float NoiseValue2, float ControlNoise, struct UCurveFloat* BlendCurve); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.BlendNoise // (Final|Native|Static|Public|BlueprintCallable|BlueprintPure) // @ game+0x864150
	float AddNoise(float NoiseValue1, float NoiseValue2, float MaskNoise, float Threshold); // Function NoisePlugin.NoiseBlueprintFunctionLibrary.AddNoise // (Final|Native|Static|Public|BlueprintCallable|BlueprintPure) // @ game+0x863ff0
};

